<?php

declare(strict_types=1);

namespace App\Console\Commands;

use Illuminate\Console\Command;

/**
 * W2-01: app() usage report.
 *
 * Generates a top-N report of files with the most app() calls,
 * grouped by namespace. Used in CI to track service-locator debt.
 *
 * Usage:
 *   php artisan app:usage-report
 *   php artisan app:usage-report --top=50 --output=docs/app-usage.md
 */
final class AppUsageReportCommand extends Command
{
    protected $signature = 'app:usage-report
                            {--top=20 : Number of top files to include}
                            {--output= : Output file path (defaults to stdout)}';

    protected $description = 'Generate a top-N app() usage report (W2-01)';

    private const APP_DIR = __DIR__.'/../../..';

    public function handle(): int
    {
        $top = (int) $this->option('top');
        $output = $this->option('output');

        $counts = $this->collectAppUsage();
        $byNamespace = $this->groupByNamespace($counts);
        $topFiles = $this->topFiles($counts, $top);

        $content = $this->formatMarkdown($counts, $byNamespace, $topFiles, $top);

        if ($output !== null && $output !== '') {
            file_put_contents($output, $content);
            $this->info("app() usage report written to {$output}");
        } else {
            $this->line($content);
        }

        return self::SUCCESS;
    }

    /**
     * @return array<string, int>
     */
    private function collectAppUsage(): array
    {
        $counts = [];
        $dir = realpath(self::APP_DIR.'/app');
        if ($dir === false) {
            return $counts;
        }

        $iterator = new \RecursiveIteratorIterator(
            new \RecursiveDirectoryIterator($dir, \FilesystemIterator::SKIP_DOTS),
        );

        foreach ($iterator as $file) {
            if (! $file->isFile() || $file->getExtension() !== 'php') {
                continue;
            }

            $content = file_get_contents($file->getPathname());
            if ($content === false) {
                continue;
            }

            $count = 0;
            foreach (explode("\n", $content) as $line) {
                if (preg_match('/\bapp\s*\(/i', $line)) {
                    $count++;
                }
            }

            if ($count > 0) {
                $relativePath = 'app/'.ltrim(str_replace($dir, '', $file->getPathname()), '/');
                $counts[$relativePath] = $count;
            }
        }

        arsort($counts);

        return $counts;
    }

    /**
     * @param  array<string, int>  $counts
     * @return array<string, int>
     */
    private function groupByNamespace(array $counts): array
    {
        $namespaces = [
            'Controllers' => 0,
            'Services' => 0,
            'Repositories' => 0,
            'Support' => 0,
            'Filament' => 0,
            'Other' => 0,
        ];

        foreach ($counts as $path => $count) {
            if (str_starts_with($path, 'app/Http/Controllers')) {
                $namespaces['Controllers'] += $count;
            } elseif (str_starts_with($path, 'app/Services')) {
                $namespaces['Services'] += $count;
            } elseif (str_starts_with($path, 'app/Repositories')) {
                $namespaces['Repositories'] += $count;
            } elseif (str_starts_with($path, 'app/Support')) {
                $namespaces['Support'] += $count;
            } elseif (str_starts_with($path, 'app/Filament')) {
                $namespaces['Filament'] += $count;
            } else {
                $namespaces['Other'] += $count;
            }
        }

        arsort($namespaces);

        return $namespaces;
    }

    /**
     * @param  array<string, int>  $counts
     * @return array<string, int>
     */
    private function topFiles(array $counts, int $top): array
    {
        return array_slice($counts, 0, $top, true);
    }

    /**
     * @param  array<string, int>  $counts
     * @param  array<string, int>  $byNamespace
     * @param  array<string, int>  $topFiles
     */
    private function formatMarkdown(array $counts, array $byNamespace, array $topFiles, int $top): string
    {
        $total = array_sum($counts);
        $lines = [
            '# app() Usage Report',
            '',
            'Generated by `php artisan app:usage-report` (W2-01).',
            '',
            'Total files with app(): '.count($counts),
            'Total app() lines: '.$total,
            '',
            '## By namespace',
            '',
            '| Namespace | app() lines |',
            '|-----------|------------:|',
        ];

        foreach ($byNamespace as $ns => $count) {
            $lines[] = "| {$ns} | {$count} |";
        }

        $lines[] = '';
        $lines[] = "## Top-{$top} files";
        $lines[] = '';
        $lines[] = '| Rank | app() lines | File |';
        $lines[] = '|-----:|------------:|------|';

        $rank = 1;
        foreach ($topFiles as $path => $count) {
            $lines[] = "| {$rank} | {$count} | `{$path}` |";
            $rank++;
        }

        return implode("\n", $lines)."\n";
    }
}
