<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SecondiconsTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {

        DB::table('secondicons')->delete();

        DB::table('secondicons')->insert([
            0 => [
                'id' => 1,
                'source' => 0,
                'medium' => 1,
                'codec' => 1,
                'standard' => 0,
                'processing' => 0,
                'audiocodec' => 0,
                'name' => 'Blu-ray/H.264',
                'class_name' => null,
                'image' => 'bdh264.png',
            ],
            1 => [
                'id' => 2,
                'source' => 0,
                'medium' => 1,
                'codec' => 2,
                'standard' => 0,
                'processing' => 0,
                'audiocodec' => 0,
                'name' => 'Blu-ray/VC-1',
                'class_name' => null,
                'image' => 'bdvc1.png',
            ],
            2 => [
                'id' => 3,
                'source' => 0,
                'medium' => 1,
                'codec' => 4,
                'standard' => 0,
                'processing' => 0,
                'audiocodec' => 0,
                'name' => 'Blu-ray/MPEG-2',
                'class_name' => null,
                'image' => 'bdmpeg2.png',
            ],
            3 => [
                'id' => 4,
                'source' => 0,
                'medium' => 2,
                'codec' => 1,
                'standard' => 0,
                'processing' => 0,
                'audiocodec' => 0,
                'name' => 'HD DVD/H.264',
                'class_name' => null,
                'image' => 'hddvdh264.png',
            ],
            4 => [
                'id' => 5,
                'source' => 0,
                'medium' => 2,
                'codec' => 2,
                'standard' => 0,
                'processing' => 0,
                'audiocodec' => 0,
                'name' => 'HD DVD/VC-1',
                'class_name' => null,
                'image' => 'hddvdvc1.png',
            ],
            5 => [
                'id' => 6,
                'source' => 0,
                'medium' => 2,
                'codec' => 4,
                'standard' => 0,
                'processing' => 0,
                'audiocodec' => 0,
                'name' => 'HD DVD/MPEG-2',
                'class_name' => null,
                'image' => 'hddvdmpeg2.png',
            ],
            6 => [
                'id' => 7,
                'source' => 0,
                'medium' => 3,
                'codec' => 1,
                'standard' => 0,
                'processing' => 0,
                'audiocodec' => 0,
                'name' => 'Remux/H.264',
                'class_name' => null,
                'image' => 'remuxh264.png',
            ],
            7 => [
                'id' => 8,
                'source' => 0,
                'medium' => 3,
                'codec' => 2,
                'standard' => 0,
                'processing' => 0,
                'audiocodec' => 0,
                'name' => 'Remux/VC-1',
                'class_name' => null,
                'image' => 'remuxvc1.png',
            ],
            8 => [
                'id' => 9,
                'source' => 0,
                'medium' => 3,
                'codec' => 4,
                'standard' => 0,
                'processing' => 0,
                'audiocodec' => 0,
                'name' => 'Remux/MPEG-2',
                'class_name' => null,
                'image' => 'remuxmpeg2.png',
            ],
            9 => [
                'id' => 10,
                'source' => 0,
                'medium' => 4,
                'codec' => 0,
                'standard' => 0,
                'processing' => 0,
                'audiocodec' => 0,
                'name' => 'AVCHD',
                'class_name' => null,
                'image' => 'avchd.png',
            ],
            10 => [
                'id' => 11,
                'source' => 0,
                'medium' => 5,
                'codec' => 1,
                'standard' => 0,
                'processing' => 0,
                'audiocodec' => 0,
                'name' => 'HDTV/H.264',
                'class_name' => null,
                'image' => 'hdtvh264.png',
            ],
            11 => [
                'id' => 12,
                'source' => 0,
                'medium' => 5,
                'codec' => 4,
                'standard' => 0,
                'processing' => 0,
                'audiocodec' => 0,
                'name' => 'HDTV/MPEG-2',
                'class_name' => null,
                'image' => 'hdtvmpeg2.png',
            ],
            12 => [
                'id' => 13,
                'source' => 0,
                'medium' => 6,
                'codec' => 0,
                'standard' => 0,
                'processing' => 0,
                'audiocodec' => 0,
                'name' => 'DVDR',
                'class_name' => null,
                'image' => 'dvdr.png',
            ],
            13 => [
                'id' => 14,
                'source' => 0,
                'medium' => 7,
                'codec' => 1,
                'standard' => 0,
                'processing' => 0,
                'audiocodec' => 0,
                'name' => 'Rip/H.264',
                'class_name' => null,
                'image' => 'riph264.png',
            ],
            14 => [
                'id' => 15,
                'source' => 0,
                'medium' => 7,
                'codec' => 3,
                'standard' => 0,
                'processing' => 0,
                'audiocodec' => 0,
                'name' => 'Rip/Xvid',
                'class_name' => null,
                'image' => 'ripxvid.png',
            ],
            15 => [
                'id' => 16,
                'source' => 0,
                'medium' => 8,
                'codec' => 5,
                'standard' => 0,
                'processing' => 0,
                'audiocodec' => 0,
                'name' => 'CD/FLAC',
                'class_name' => null,
                'image' => 'cdflac.png',
            ],
            16 => [
                'id' => 17,
                'source' => 0,
                'medium' => 8,
                'codec' => 6,
                'standard' => 0,
                'processing' => 0,
                'audiocodec' => 0,
                'name' => 'CD/APE',
                'class_name' => null,
                'image' => 'cdape.png',
            ],
            17 => [
                'id' => 18,
                'source' => 0,
                'medium' => 8,
                'codec' => 7,
                'standard' => 0,
                'processing' => 0,
                'audiocodec' => 0,
                'name' => 'CD/DTS',
                'class_name' => null,
                'image' => 'cddts.png',
            ],
            18 => [
                'id' => 19,
                'source' => 0,
                'medium' => 8,
                'codec' => 9,
                'standard' => 0,
                'processing' => 0,
                'audiocodec' => 0,
                'name' => 'CD/Other',
                'class_name' => null,
                'image' => 'cdother.png',
            ],
            19 => [
                'id' => 20,
                'source' => 0,
                'medium' => 9,
                'codec' => 5,
                'standard' => 0,
                'processing' => 0,
                'audiocodec' => 0,
                'name' => 'Extract/FLAC',
                'class_name' => null,
                'image' => 'extractflac.png',
            ],
            20 => [
                'id' => 21,
                'source' => 0,
                'medium' => 9,
                'codec' => 7,
                'standard' => 0,
                'processing' => 0,
                'audiocodec' => 0,
                'name' => 'Extract/DTS',
                'class_name' => null,
                'image' => 'extractdts.png',
            ],
            21 => [
                'id' => 22,
                'source' => 0,
                'medium' => 9,
                'codec' => 8,
                'standard' => 0,
                'processing' => 0,
                'audiocodec' => 0,
                'name' => 'Extract/AC-3',
                'class_name' => null,
                'image' => 'extractac3.png',
            ],
        ]);

    }
}
