{{-- Bonus exchange shop — replaces the ob_start/echo table from
     BonusPageService::buildShopTable. One form per row, same field names. --}}
<table align="center" width="97%" border="1" cellspacing="0" cellpadding="3" data-nx="data">
<tr><td class="colhead" colspan="4" align="center"><span class="big">{{ $shop->sitename }}{{ __('legacy/mybonus.text_karma_system') }}</span></td></tr>
@if ((string) $shop->msg !== '')
<tr><td align="center" colspan="4"><span class="striking"><b>{{ $shop->msg }}</b></span></td></tr>
@endif
<tr><td class="text" align="center" colspan="4">{{ __('legacy/mybonus.text_exchange_your_karma') }}{{ $shop->bonus }}{{ __('legacy/mybonus.text_for_goodies') }}<br /><b>{{ __('legacy/mybonus.text_no_buttons_note') }}</b><br /><small>({{ $shop->lockText }})</small></td></tr>
<tr><td class="colhead" align="center">{{ __('legacy/mybonus.col_option') }}</td><td class="colhead" align="left">{{ __('legacy/mybonus.col_description') }}</td><td class="colhead" align="center">{{ __('legacy/mybonus.col_points') }}</td><td class="colhead" align="center">{{ __('legacy/mybonus.col_trade') }}</td></tr>
@foreach ($shop->items as $item)
<tr><form action="?action=exchange" method="post"><td class="rowhead_center"><input type="hidden" name="option" value="{{ $item->index }}" /><b>{{ $item->index + 1 }}</b></td><td class="rowfollow" align="left"><h1>{{ $item->name }}</h1>{{ $item->description }}@if ($item->art === 'title')<br /><br />{{ \App\Support\Html\SafeHtml::fromUntrustedHtml(__('legacy/mybonus.text_enter_titile')) }}<input type="text" name="title" maxlength="30" />{{ __('legacy/mybonus.text_click_exchange') }}@elseif ($item->art === 'gift_1')<br /><br />{{ \App\Support\Html\SafeHtml::fromUntrustedHtml(__('legacy/mybonus.text_enter_receiver_name')) }}<br /><div class="nx-giftfields"><span><b>{{ __('legacy/mybonus.text_username') }}</b><input type="text" name="username" maxlength="24" /></span><span><b>{{ __('legacy/mybonus.text_to_be_given') }}</b><input type="number" name="bonusgift" id="giftcustom" min="100" />{{ __('legacy/mybonus.text_karma_points') }}</span><span><b>{{ __('legacy/mybonus.text_message') }}</b><input type="text" name="message" maxlength="100" /></span></div>@elseif ($item->art === 'gift_2')<br /><br />{{ \App\Support\Html\SafeHtml::fromUntrustedHtml(__('legacy/mybonus.text_select_receiver_ratio')) }}<br /><div class="nx-giftfields"><span>{{ __('legacy/mybonus.text_ratio_below') }}<select name="ratiocharity"><option value="0.1"> 0.1</option><option value="0.2"> 0.2</option><option value="0.3" selected="selected"> 0.3</option><option value="0.4"> 0.4</option><option value="0.5"> 0.5</option><option value="0.6"> 0.6</option><option value="0.7"> 0.7</option><option value="0.8"> 0.8</option></select>{{ __('legacy/mybonus.text_and_downloaded_above') }} 10 GB</span><span><b>{{ __('legacy/mybonus.text_to_be_given') }}</b><select name="bonuscharity" id="charityselect"><option value="1000"> 1,000</option><option value="2000"> 2,000</option><option value="3000" selected="selected"> 3000</option><option value="5000"> 5,000</option><option value="8000"> 8,000</option><option value="10000"> 10,000</option><option value="20000"> 20,000</option><option value="50000"> 50,000</option></select>{{ __('legacy/mybonus.text_karma_points') }}</span></div>@endif</td><td class="rowfollow{{ in_array($item->art, ['gift_1', 'gift_2'], true) ? ' nowrap' : '' }}" align="center">{{ $item->pointsLabel }}</td><td class="rowfollow" align="center"><input type="submit" name="submit" value="{{ $item->trade->label }}"@if ($item->trade->disabled) disabled="disabled"@endif /></td></form></tr>
@endforeach
</table><br />
