{{-- Bonus exchange shop — replaces the ob_start/echo table from
     BonusPageService::buildShopTable. One form per row, same field names. --}}
<x-data-table :caption="$shop->sitename.__('legacy/mybonus.text_karma_system')" :caption-hidden="true">
    <x-slot:head>
        <thead>
            <tr><th class="text-center" scope="col">{{ __('legacy/mybonus.col_option') }}</th><th scope="col">{{ __('legacy/mybonus.col_description') }}</th><th class="text-center" scope="col">{{ __('legacy/mybonus.col_points') }}</th><th class="text-center" scope="col">{{ __('legacy/mybonus.col_trade') }}</th></tr>
        </thead>
    </x-slot:head>
<tr><td class="text-center font-bold" colspan="4"><span class="big">{{ $shop->sitename }}{{ __('legacy/mybonus.text_karma_system') }}</span></td></tr>
@if ((string) $shop->msg !== '')
<tr><td class="text-center" colspan="4"><span class="striking"><b>{{ $shop->msg }}</b></span></td></tr>
@endif
<tr><td class="text-center" colspan="4">{{ __('legacy/mybonus.text_exchange_your_karma') }}{{ $shop->bonus }}{{ __('legacy/mybonus.text_for_goodies') }}<br /><b>{{ __('legacy/mybonus.text_no_buttons_note') }}</b><br /><small>({{ $shop->lockText }})</small></td></tr>
@foreach ($shop->items as $item)
<tr><td class="text-center align-top px-2.5 py-1.5 font-semibold text-nxm-text-dim"><form id="bx{{ $item->index }}" action="?action=exchange" method="post"></form><input form="bx{{ $item->index }}" type="hidden" name="option" value="{{ $item->index }}" /><b>{{ $item->index + 1 }}</b></td><td class="align-top px-2.5 py-1.5"><h1>{{ $item->name }}</h1>{{ $item->description }}@if ($item->giftTax !== null)<br /><br />{{ $item->giftTax['charges'] }}<b>{{ $item->giftTax['amounts'] }}</b>{{ $item->giftTax['rest'] }}@endif@if ($item->art === 'title')<br /><br />{{ __('legacy/mybonus.text_enter_titile') }}<b>{{ __('legacy/mybonus.text_special_title') }}</b>{{ __('legacy/mybonus.text_you_would_like') }}<input form="bx{{ $item->index }}" type="text" name="title" maxlength="30" />{{ __('legacy/mybonus.text_click_exchange') }}@elseif ($item->art === 'gift_1')<br /><br />{{ __('legacy/mybonus.text_enter_receiver_name') }}<b>{{ __('legacy/mybonus.text_username_word') }}</b>{{ __('legacy/mybonus.text_enter_receiver_name_tail') }}<br /><div class="nx-giftfields"><span><b>{{ __('legacy/mybonus.text_username') }}</b><input form="bx{{ $item->index }}" type="text" name="username" maxlength="24" /></span><span><b>{{ __('legacy/mybonus.text_to_be_given') }}</b><input form="bx{{ $item->index }}" type="number" name="bonusgift" id="giftcustom" min="100" />{{ __('legacy/mybonus.text_karma_points') }}</span><span><b>{{ __('legacy/mybonus.text_message') }}</b><input form="bx{{ $item->index }}" type="text" name="message" maxlength="100" /></span></div>@elseif ($item->art === 'gift_2')<br /><br />{{ __('legacy/mybonus.text_select_receiver_ratio') }}<b>{{ __('legacy/mybonus.text_ratio_word') }}</b>{{ __('legacy/mybonus.text_select_receiver_ratio_tail') }}<br /><div class="nx-giftfields"><span>{{ __('legacy/mybonus.text_ratio_below') }}<select form="bx{{ $item->index }}" name="ratiocharity"><option value="0.1"> 0.1</option><option value="0.2"> 0.2</option><option value="0.3" selected="selected"> 0.3</option><option value="0.4"> 0.4</option><option value="0.5"> 0.5</option><option value="0.6"> 0.6</option><option value="0.7"> 0.7</option><option value="0.8"> 0.8</option></select>{{ __('legacy/mybonus.text_and_downloaded_above') }} 10 GB</span><span><b>{{ __('legacy/mybonus.text_to_be_given') }}</b><select form="bx{{ $item->index }}" name="bonuscharity" id="charityselect"><option value="1000"> 1,000</option><option value="2000"> 2,000</option><option value="3000" selected="selected"> 3000</option><option value="5000"> 5,000</option><option value="8000"> 8,000</option><option value="10000"> 10,000</option><option value="20000"> 20,000</option><option value="50000"> 50,000</option></select>{{ __('legacy/mybonus.text_karma_points') }}</span></div>@elseif ($item->art === 'cancel_hr')<p>
            <span>{{ __('legacy/mybonus.text_cancel_hr_label') }}</span>
            <input form="bx{{ $item->index }}" type="number" name="hr_id" />
        </p>@endif</td><td class="text-center{{ in_array($item->art, ['gift_1', 'gift_2'], true) ? ' whitespace-nowrap' : '' }}">{{ $item->pointsLabel }}@if ($item->pointsLabel2 !== null)<br />{{ $item->pointsLabel2 }}@endif</td><td class="text-center"><input form="bx{{ $item->index }}" type="submit" name="submit" value="{{ $item->trade->label }}"@if ($item->trade->disabled) disabled="disabled"@endif /></td></tr>
@endforeach
</x-data-table><br />
