@include('usercp.sections._menu', ['selected' => 'tracker'])

<form method=post action=usercp.php id="{{ $tracker->formId }}"><input type=hidden name=action value=tracker><input type=hidden name=type value=save>
<div class="nx-fgrid nx-fgrid--flat">
@if ($type === 'saved')
<div class="nx-ffull text-center"><span class="text-nxm-danger"><b>{{ __('legacy/usercp.text_saved')}}</b></span></div>
@endif
@if ($tracker->showEmailNotify)
<x-settings-row-small layout="grid" :label="\App\Support\Html\SafeHtml::fromUntrustedHtml(__('legacy/usercp.row_email_notification'))"><input type="checkbox" name="pmnotif"@if ($tracker->pmnotif) checked @endif value="yes"> {{ __('legacy/usercp.checkbox_notification_received_pm') }}<br />
<input type="checkbox" name="emailnotif"@if ($tracker->emailnotif) checked @endif value="yes" /> {{ __('legacy/usercp.checkbox_notification_default_categories') }}</x-settings-row-small>
@endif
<x-settings-row-small layout="grid" :label="view('usercp._default-categories-label')"><x-search-category-table :vm="$tracker->categoriesTable" /><div></div>
<div class="nx-cat-extra"><span class="big">{{ __('legacy/usercp.text_additional_selection') }}</span><div><b>{{ __('legacy/usercp.text_show_dead_active') }}</b><br /><select name="incldead"><option value="0"@if ($tracker->incldead === 0) selected @endif>{{ __('legacy/usercp.select_including_dead') }}</option><option value="1"@if ($tracker->incldead === 1) selected @endif>{{ __('legacy/usercp.select_active') }}</option><option value="2"@if ($tracker->incldead === 2) selected @endif>{{ __('legacy/usercp.select_dead') }}</option></select></div><div><b>{{ __('legacy/usercp.text_show_special_torrents') }}</b><br /><select name="spstate"><option value="0"@if ($tracker->specialState === 0) selected @endif>{{ __('legacy/usercp.select_all') }}</option>{{ $tracker->promotionOptionsHtml }}</select></div><div><b>{{ __('legacy/usercp.text_show_bookmarked') }}</b><br /><select name="inclbookmarked"><option value="0"@if ($tracker->inclbookmarked === 0) selected @endif>{{ __('legacy/usercp.select_all') }}</option><option value="1"@if ($tracker->inclbookmarked === 1) selected @endif>{{ __('legacy/usercp.select_bookmarked') }}</option><option value="2"@if ($tracker->inclbookmarked === 2) selected @endif>{{ __('legacy/usercp.select_bookmarked_exclude') }}</option></select></div></div></x-settings-row-small>
<x-settings-select layout="grid" :label="__('legacy/usercp.row_stylesheet')" name="stylesheet" :options="$tracker->stylesheetOptions" :selected="$tracker->currentStylesheet" />
<x-settings-select layout="grid" :label="__('legacy/usercp.row_theme')" name="theme" :options="$tracker->themeOptions" :selected="$tracker->currentTheme" />
<x-settings-select layout="grid" :label="__('legacy/usercp.row_font_size')" name="fontsize" :options="['small' => __('legacy/usercp.select_small'), 'medium' => __('legacy/usercp.select_medium'), 'large' => __('legacy/usercp.select_large')]" :selected="$tracker->fontsize" />
<x-settings-row-small layout="grid" :label="__('legacy/usercp.row_site_language')"><select name="sitelanguage">
@foreach ($tracker->langOptions as $id => $name)
<option value="{{ $id }}"@if ($tracker->currentLangId === (int) $id) selected @endif>{{ $name }}</option>
@endforeach
</select>&nbsp;&nbsp;<span class="small">{{ __('legacy/usercp.text_translation_note') }}<a href="aboutnexus.php#translation"><b>{{ __('legacy/usercp.text_translation_link') }}</b></a></span>.</x-settings-row-small>
<x-settings-row-small layout="grid" :label="__('legacy/usercp.row_pm_boxes')">{{ __('legacy/usercp.text_show') }}<input type="text" name="pmnum" size="5" value="{{ $tracker->pmnum }}"> {{ __('legacy/usercp.text_pms_per_page') }}</x-settings-row-small>
@if ($tracker->showShoutbox)
<x-settings-row-small layout="grid" :label="__('legacy/usercp.row_shoutbox')">{{ __('legacy/usercp.text_show_last') }}<input type="text" name="sbnum" size="5" value="{{ $tracker->sbnum }}"> {{ __('legacy/usercp.text_messages_at_shoutbox') }}<br />{{ __('legacy/usercp.text_refresh_shoutbox_every') }}<input type="text" name="sbrefresh" size="5" value="{{ $tracker->sbrefresh }}"> {{ __('legacy/usercp.text_seconds') }}</x-settings-row-small>
@endif
<x-settings-row-small layout="grid" :label="__('legacy/usercp.row_torrent_detail')"><input type="checkbox" name="showdescription"@if ($tracker->showdescription) checked @endif value="yes">{{ __('legacy/usercp.text_show_description') }}</x-settings-row-small>
<x-settings-row-small layout="grid" :label="__('legacy/usercp.row_discuss')"><input type="checkbox" name="showcomment"@if ($tracker->showcomment) checked @endif value="yes">{{ __('legacy/usercp.text_show_comments') }}</x-settings-row-small>
<x-settings-radios layout="grid" :label="__('legacy/usercp.row_time_type')" name="timetype" :options="['timeadded' => __('legacy/usercp.text_time_added'), 'timealive' => __('legacy/usercp.text_time_elapsed')]" :selected="$tracker->timetype" />
<x-settings-row-small layout="grid" :label="__('legacy/usercp.row_browse_page')"><span class='striking'><b>{{ __('legacy/usercp.text_warning') }}: </b></span>{{ __('legacy/usercp.text_browse_setting_warning') }}
<br /><b>{{ \App\Support\Html\SafeHtml::fromUntrustedHtml(__('legacy/usercp.row_torrent_page')) }}: </b><br />{{ __('legacy/usercp.text_show') }}<input type="text" size="5" name="torrentsperpage" value="{{ $tracker->torrentsperpage }}"> {{ __('legacy/usercp.text_torrents_per_page') }}{{ __('legacy/usercp.text_zero_equals_default') }}<br />
@if ($tracker->showTooltipSetting)<b>{{ __('legacy/usercp.text_tooltip_type') }}</b>: <br /><input type="radio" name="tooltip"@if ($tracker->tooltip === 'off') checked @endif value="off">{{ __('legacy/usercp.text_off') }}<br />@endif
<b>{{ __('legacy/usercp.text_append_words_to_torrents') }}: </b><br /><input type="checkbox" name="appendsticky"@if ($tracker->appendsticky) checked @endif value="yes">{{ __('legacy/usercp.text_append_sticky') }}<img class="sticky" src="pic/trans.gif" alt="sticky" />{{ __('legacy/usercp.text_append_sticky_tail') }}<br /><input type="checkbox" name="appendnew"@if ($tracker->appendnew) checked @endif value="yes">{{ __('legacy/usercp.text_append_new') }}<br />{{ __('legacy/usercp.text_torrents_on_promotion') }}<input type="radio" name="appendpromotion"@if ($tracker->appendpromotion === 'highlight') checked @endif value="highlight">{{ __('legacy/usercp.text_highlight') }}<input type="radio" name="appendpromotion"@if ($tracker->appendpromotion === 'word') checked @endif value="word">{{ __('legacy/usercp.text_append_words') }}<input type="radio" name="appendpromotion"@if ($tracker->appendpromotion === 'icon') checked @endif value="icon">{{ __('legacy/usercp.text_append_icon') }}<span class="nx-promo nx-promo--free">{{ __('legacy/functions.text_free') }}</span><input type="radio" name="appendpromotion"@if ($tracker->appendpromotion === 'off') checked @endif value="off">{{ __('legacy/usercp.text_no_mark') }}<br /><input type="checkbox" name="appendpicked"@if ($tracker->appendpicked) checked @endif value="yes">{{ __('legacy/usercp.text_append_picked') }}<br />
<b>{{ __('legacy/usercp.text_show_action_icons') }}: </b><br /><input type="checkbox" name="dlicon"@if ($tracker->dlicon) checked @endif value="yes">{{ __('legacy/usercp.text_show_download_icon') }} <img class="download" src="pic/trans.gif" alt="Download" /><br /><input type="checkbox" name="bmicon"@if ($tracker->bmicon) checked @endif value="yes">{{ __('legacy/usercp.text_show_bookmark_icon') }} <img class="bookmark" src="pic/trans.gif" alt="Bookmark" /><br />
<b>{{ __('legacy/usercp.text_comments_reviews') }}: </b><br /><input type="checkbox" name="showcomnum"@if ($tracker->showcomnum) checked @endif value="yes">{{ \App\Support\Html\SafeHtml::fromUntrustedHtml(__('legacy/usercp.text_show_comment_number')) }}@if ($tracker->showTooltipSetting)<select name="showlastcom"><option value="yes"@if ($tracker->showlastcom) selected @endif>{{ __('legacy/usercp.select_with') }}</option><option value="no"@if (! $tracker->showlastcom) selected @endif>{{ __('legacy/usercp.select_without') }}</option></select>{{ \App\Support\Html\SafeHtml::fromUntrustedHtml(__('legacy/usercp.text_last_comment_on_tooltip')) }}@endif</x-settings-row-small>
<div class="nx-fhead">{{ __('legacy/usercp.row_save_settings')}}</div><div class="nx-fcell"><input type=submit value="{{ __('legacy/usercp.submit_save_settings')}}"></div>
</div></form>
