<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\AdminController;
use App\Http\Controllers\BitbucketUploadController;
use App\Http\Controllers\BonusController;
use App\Http\Controllers\ForumController;
use App\Http\Controllers\FriendsController;
use App\Http\Controllers\IndexController;
use App\Http\Controllers\InfoController;
use App\Http\Controllers\LogController;
use App\Http\Controllers\MessageController;
use App\Http\Controllers\ModerationController;
use App\Http\Controllers\MyController;
use App\Http\Controllers\OfferController;
use App\Http\Controllers\ShoutboxController;
use App\Http\Controllers\StaffController;
use App\Http\Controllers\SystemController;
use App\Http\Controllers\ToptenController;
use App\Http\Controllers\TorrentActionController;
use App\Http\Controllers\TorrentDetailsController;
use App\Http\Controllers\TorrentListingController;
use App\Http\Controllers\TorrentUploadController;
use App\Http\Controllers\UtilityController;
use App\Http\Controllers\WebCommentController;

    Route::get('/upload', [TorrentUploadController::class, 'create'])->name('torrents.upload');
    Route::get('/bitbucket-upload', [BitbucketUploadController::class, 'create'])->name('bitbucket.upload');
    Route::post('/bitbucket-upload', [BitbucketUploadController::class, 'store']);
    Route::match(['get', 'post'], '/offers', [OfferController::class, 'legacy'])->name('offers.legacy');
    Route::get('/torrents', [TorrentListingController::class, 'index'])->name('torrents.index');
    Route::get('/special', [TorrentListingController::class, 'index'])->name('torrents.special');
    Route::get('/details/{id}', [TorrentDetailsController::class, 'show'])->where('id', '[0-9]+')->name('torrent.details');
    Route::match(['get', 'post'], '/mybonus', [MyController::class, 'bonus'])->name('my.bonus');
    Route::get('/myhr', [MyController::class, 'hr'])->name('my.hr');
    Route::get('/topten', [ToptenController::class, 'legacy'])->name('topten.legacy');
    Route::get('/log', [LogController::class, 'legacy'])->name('log.legacy');
    Route::match(['get', 'post'], '/index', [IndexController::class, 'legacy'])->name('index.legacy');
    Route::match(['get', 'post'], '/friends', [FriendsController::class, 'friends'])->name('friends.legacy');
    Route::match(['get', 'post'], '/messages', [MessageController::class, 'messages'])->name('messages.legacy');
    Route::match(['get', 'post'], '/getrss', [InfoController::class, 'getrss'])->name('getrss.legacy');
    Route::match(['get', 'post'], '/sendmessage', [MessageController::class, 'sendmessage'])->name('sendmessage.legacy');
    Route::match(['get', 'post'], '/userhistory', [InfoController::class, 'userhistory'])->name('userhistory.legacy');
    Route::match(['get', 'post'], '/invite', [InfoController::class, 'invite'])->name('invite.legacy');
    Route::match(['get', 'post'], '/news', [InfoController::class, 'news'])->name('news.legacy');
    Route::match(['get', 'post'], '/makepoll', [InfoController::class, 'makepoll'])->name('makepoll.legacy');
    Route::match(['get', 'post'], '/polloverview', [InfoController::class, 'polloverview'])->name('polloverview.legacy');
    Route::match(['get', 'post'], '/attendance', [InfoController::class, 'attendance'])->name('attendance.legacy');
    Route::match(['get', 'post'], '/takemessage', [MessageController::class, 'takeMessage'])->name('takemessage.legacy');
    Route::match(['get', 'post'], '/deletemessage', [MessageController::class, 'deletemessage'])->name('deletemessage.legacy');
    Route::match(['get', 'post'], '/report', [ModerationController::class, 'report'])->name('report.legacy');
    Route::match(['get', 'post'], '/reports', [ModerationController::class, 'reports'])->name('reports.legacy');
    Route::match(['get', 'post'], '/bans', [ModerationController::class, 'bans'])->name('bans.legacy');
    Route::match(['get', 'post'], '/cheaterbox', [ModerationController::class, 'cheaterbox'])->name('cheaterbox.legacy');
    Route::match(['get', 'post'], '/cheaters', [ModerationController::class, 'cheaters'])->name('cheaters.legacy');
    Route::match(['get', 'post'], '/iphistory', [ModerationController::class, 'iphistory'])->name('iphistory.legacy');
    Route::match(['get', 'post'], '/ipcheck', [ModerationController::class, 'ipcheck'])->name('ipcheck.legacy');
    Route::match(['get', 'post'], '/ipsearch', [ModerationController::class, 'ipsearch'])->name('ipsearch.legacy');
    Route::match(['get', 'post'], '/modtask', [StaffController::class, 'modtask'])->name('modtask.legacy');
    Route::match(['get', 'post'], '/staff', [StaffController::class, 'staff'])->name('staff.legacy');
    Route::match(['get', 'post'], '/staffbox', [StaffController::class, 'staffbox'])->name('staffbox.legacy');
    Route::match(['get', 'post'], '/staffmess', [StaffController::class, 'staffmess'])->name('staffmess.legacy');
    Route::match(['get', 'post'], '/takestaffmess', [StaffController::class, 'takeStaffmess'])->name('takestaffmess.legacy');
    Route::match(['get', 'post'], '/contactstaff', [StaffController::class, 'contactstaff'])->name('contactstaff.legacy');
    Route::match(['get', 'post'], '/takecontact', [StaffController::class, 'takecontact'])->name('takecontact.legacy');
    Route::match(['get', 'post'], '/modrules', [StaffController::class, 'modrules'])->name('modrules.legacy');
    Route::match(['get', 'post'], '/donorlist', [AdminController::class, 'donorlist'])->name('donorlist.legacy');
    Route::match(['get', 'post'], '/stats', [AdminController::class, 'stats'])->name('stats.legacy');
    Route::match(['get', 'post'], '/warned', [AdminController::class, 'warned'])->name('warned.legacy');
    Route::match(['get', 'post'], '/nowarn', [AdminController::class, 'nowarn'])->name('nowarn.legacy');
    Route::match(['get', 'post'], '/allagents', [AdminController::class, 'allagents'])->name('allagents.legacy');

    Route::match(['get', 'post'], '/checkuser', [AdminController::class, 'checkuser'])->name('checkuser.legacy');
    Route::match(['get', 'post'], '/takeconfirm', [AdminController::class, 'takeconfirm'])->name('takeconfirm.legacy');
    Route::match(['get', 'post'], '/user-ban-log', [AdminController::class, 'userBanLog'])->name('user-ban-log.legacy');
    Route::match(['get', 'post'], '/torrent_info', [TorrentActionController::class, 'torrentInfo'])->name('torrent_info.legacy');
    Route::match(['get', 'post'], '/viewsnatches', [TorrentActionController::class, 'viewSnatches'])->name('viewsnatches.legacy');
    Route::match(['get', 'post'], '/takeflush', [TorrentActionController::class, 'takeFlush'])->name('takeflush.legacy');
    Route::match(['get', 'post'], '/takereseed', [TorrentActionController::class, 'takeReseed'])->name('takereseed.legacy');
    Route::match(['get', 'post'], '/clearcache', [AdminController::class, 'clearCache'])->name('clearcache.legacy');
    Route::match(['get', 'post'], '/fastdelete', [TorrentActionController::class, 'fastDelete'])->name('fastdelete.legacy');
    Route::match(['get', 'post'], '/donated', [InfoController::class, 'donated'])->name('donated.legacy');
    Route::match(['get', 'post'], '/faqmanage', [InfoController::class, 'faqManage'])->name('faqmanage.legacy');
    Route::match(['get', 'post'], '/faqactions', [InfoController::class, 'faqActions'])->name('faqactions.legacy');
    Route::match(['get', 'post'], '/search', [UtilityController::class, 'search'])->name('search.legacy');
    Route::match(['get', 'post'], '/usersearch', [UtilityController::class, 'usersearch'])->name('usersearch.legacy');
    Route::match(['get', 'post'], '/autocomplete_torrents', [TorrentActionController::class, 'autocompleteTorrents'])->name('autocomplete_torrents.legacy');
    Route::get('/comment/add', [WebCommentController::class, 'create']);
    Route::post('/comment', [WebCommentController::class, 'store']);
    Route::get('/comment/{commentId}/edit', [WebCommentController::class, 'edit']);
    Route::post('/comment/{commentId}/edit', [WebCommentController::class, 'update']);
    Route::get('/comment/{commentId}/delete', [WebCommentController::class, 'destroy']);
    Route::get('/comment/{commentId}/original', [WebCommentController::class, 'original']);
    Route::match(['get', 'post'], '/catmanage', [AdminController::class, 'catmanage'])->name('catmanage.legacy');
    Route::match(['get', 'post'], '/forummanage', [ForumController::class, 'forummanage'])->name('forummanage.legacy');
    Route::match(['get', 'post'], '/moforums', [ForumController::class, 'moforums'])->name('moforums.legacy');
    Route::match(['get', 'post'], '/fields', [AdminController::class, 'fields'])->name('fields.legacy');
    Route::match(['get', 'post'], '/formats', [AdminController::class, 'formats'])->name('formats.legacy');
    Route::match(['get', 'post'], '/videoformats', [AdminController::class, 'videoformats'])->name('videoformats.legacy');
    Route::match(['get', 'post'], '/attachment', [UtilityController::class, 'attachment'])->name('attachment.legacy');
    Route::match(['get', 'post'], '/getattachment', [UtilityController::class, 'getattachment'])->name('getattachment.legacy');
    Route::match(['get', 'post'], '/shoutbox_history', [ShoutboxController::class, 'shoutboxHistory'])->name('shoutbox_history.legacy');
    Route::match(['get', 'post'], '/latestcomments', [ForumController::class, 'latestcomments'])->name('latestcomments.legacy');
    Route::match(['get', 'post'], '/bonus-log', [BonusController::class, 'bonusLog'])->name('bonus-log.legacy');
    Route::match(['get', 'post'], '/medal', [BonusController::class, 'medal'])->name('medal.legacy');
    Route::match(['get', 'post'], '/task', [BonusController::class, 'task'])->name('task.legacy');
    Route::match(['get', 'post'], '/uploaders', [BonusController::class, 'uploaders'])->name('uploaders.legacy');
    Route::match(['get', 'post'], '/settings', [AdminController::class, 'settings'])->name('settings.legacy');
    Route::match(['get', 'post'], '/freeleech', [BonusController::class, 'freeleech'])->name('freeleech.legacy');
    Route::match(['get', 'post'], '/magic', [BonusController::class, 'magic'])->name('magic.legacy');
    Route::match(['get', 'post'], '/delacctadmin', [SystemController::class, 'delacctadmin'])->name('delacctadmin.legacy');
    Route::match(['get', 'post'], '/deletedisabled', [SystemController::class, 'deletedisabled'])->name('deletedisabled.legacy');
    Route::match(['get', 'post'], '/massmail', [SystemController::class, 'massmail'])->name('massmail.legacy');
    Route::match(['get', 'post'], '/takeamountupload', [SystemController::class, 'takeamountupload'])->name('takeamountupload.legacy');
    Route::match(['get', 'post'], '/takeinvite', [SystemController::class, 'takeinvite'])->name('takeinvite.legacy');
    Route::match(['get', 'post'], '/takeupdate', [SystemController::class, 'takeupdate'])->name('takeupdate.legacy');
    Route::match(['get', 'post'], '/users', [AdminController::class, 'users'])->name('users.legacy');
    Route::match(['get', 'post'], '/staffpanel', [StaffController::class, 'staffpanel'])->name('staffpanel.legacy');
    Route::match(['get', 'post'], '/docleanup', [SystemController::class, 'docleanup'])->name('docleanup.legacy');
    Route::match(['get', 'post'], '/location', [AdminController::class, 'location'])->name('location.legacy');
    Route::match(['get', 'post'], '/preview', [UtilityController::class, 'preview'])->name('preview.legacy');
    Route::match(['get', 'post'], '/moresmilies', [UtilityController::class, 'moresmilies'])->name('moresmilies.legacy');
    Route::match(['get', 'post'], '/smilies', [UtilityController::class, 'smilies'])->name('smilies.legacy');
    Route::match(['get', 'post'], '/mailtest', [SystemController::class, 'mailtest'])->name('mailtest.legacy');
    Route::match(['get', 'post'], '/mysql_stats', [SystemController::class, 'mysqlStats'])->name('mysql_stats.legacy');
    Route::match(['get', 'post'], '/reset', [AdminController::class, 'reset'])->name('reset.legacy');
    Route::match(['get', 'post'], '/self-enable', [AdminController::class, 'selfEnable'])->name('self-enable.legacy');
    Route::match(['get', 'post'], '/unco', [AdminController::class, 'unco'])->name('unco.legacy');
    Route::match(['get', 'post'], '/adduser', [AdminController::class, 'adduser'])->name('adduser.legacy');
    Route::match(['get', 'post'], '/bitbucketlog', [InfoController::class, 'bitbucketlog'])->name('bitbucketlog.legacy');
    Route::match(['get', 'post'], '/delete', [TorrentActionController::class, 'delete'])->name('delete.legacy');
    Route::match(['get', 'post'], '/downloadnotice', [TorrentActionController::class, 'downloadnotice'])->name('downloadnotice.legacy');
    Route::match(['get', 'post'], '/increment-bulk', [SystemController::class, 'incrementBulk'])->name('increment-bulk.legacy');
    Route::match(['get', 'post'], '/maxlogin', [SystemController::class, 'maxlogin'])->name('maxlogin.legacy');
    Route::match(['get', 'post'], '/setlist_lookup', [SystemController::class, 'setlistLookup'])->name('setlist_lookup.legacy');
    Route::match(['get', 'post'], '/take-increment-bulk', [SystemController::class, 'takeIncrementBulk'])->name('take-increment-bulk.legacy');
    Route::match(['get', 'post'], '/testip', [AdminController::class, 'testip'])->name('testip.legacy');