<?php

declare(strict_types=1);

namespace Tests\Concerns;

use App\Support\Globals;
use App\Support\Settings;

trait SeedsLegacySettings
{
    /** @var array<string, string> */
    private const LEGACY_SETTING_KEYS = [
        'BASEURL' => 'basic.BASEURL',
        'BITCOINADDRESS' => 'main.BITCOINADDRESS',
        'ETHEREUMADDRESS' => 'main.ETHEREUMADDRESS',
        'PAYPALACCOUNT' => 'main.PAYPALACCOUNT',
        'REPORTMAIL' => 'main.reportemail',
        'SITEEMAIL' => 'main.SITEEMAIL',
        'SITENAME' => 'basic.SITENAME',
        'SITE_ONLINE' => 'main.site_online',
        'SLOGAN' => 'main.SLOGAN',
        'USDTADDRESS' => 'main.USDTADDRESS',
        'accountname' => 'smtp.accountname',
        'accountpassword' => 'smtp.accountpassword',
        'addcomment_bonus' => 'bonus.addcomment',
        'addoffer_class' => 'authority.addoffer',
        'againstoffer_class' => 'authority.againstoffer',
        'altname_main' => 'main.altname',
        'altthumbheight_attachment' => 'attachment.altthumbheight',
        'altthumbwidth_attachment' => 'attachment.altthumbwidth',
        'analyticscode_tweak' => 'tweak.analyticscode',
        'announce_url' => 'basic.announce_url',
        'askreseed_class' => 'authority.askreseed',
        'autoclean_interval_five' => 'main.autoclean_interval_five',
        'autoclean_interval_four' => 'main.autoclean_interval_four',
        'autoclean_interval_one' => 'main.autoclean_interval_one',
        'autoclean_interval_three' => 'main.autoclean_interval_three',
        'autoclean_interval_two' => 'main.autoclean_interval_two',
        'basictax_bonus' => 'bonus.basictax',
        'beanonymous_class' => 'authority.beanonymous',
        'bitbucket' => 'main.bitbucket',
        'bonus_tweak' => 'tweak.bonus',
        'bonusgift_bonus' => 'bonus.bonusgift',
        'browsecatmode' => 'main.browsecat',
        'buyinvite_class' => 'authority.buyinvite',
        'bzero_bonus' => 'bonus.bzero',
        'cheaterdet_security' => 'security.cheaterdet',
        'chrmanage_class' => 'authority.chrmanage',
        'classfour_attachment' => 'attachment.classfour',
        'classone_attachment' => 'attachment.classone',
        'classthree_attachment' => 'attachment.classthree',
        'classtwo_attachment' => 'attachment.classtwo',
        'commanage_class' => 'authority.commanage',
        'confilog_class' => 'authority.confilog',
        'countfour_attachment' => 'attachment.countfour',
        'countone_attachment' => 'attachment.countone',
        'countthree_attachment' => 'attachment.countthree',
        'counttwo_attachment' => 'attachment.counttwo',
        'cruprfmanage_class' => 'authority.cruprfmanage',
        'cssdate_tweak' => 'tweak.cssdate',
        'cuderatio_account' => 'account.cuderatio',
        'cudl_account' => 'account.cudl',
        'cuprratio_account' => 'account.cuprratio',
        'customtitle_bonus' => 'bonus.customtitle',
        'cutime_account' => 'account.cutime',
        'datefounded' => 'tweak.datefounded',
        'defaultclass_class' => 'authority.defaultclass',
        'defcss' => 'main.defstylesheet',
        'deflang' => 'main.defaultlang',
        'deldeadtorrent_torrent' => 'torrent.deldeadtorrent',
        'deletenotransfer_account' => 'account.deletenotransfer',
        'deletenotransfertwo_account' => 'account.deletenotransfertwo',
        'deletepacked_account' => 'account.deletepacked',
        'deletepeasant_account' => 'account.deletepeasant',
        'deleteunpacked_account' => 'account.deleteunpacked',
        'delownsub_class' => 'authority.delownsub',
        'disableemailchange' => 'security.changeemail',
        'dlamountlimit_bonus' => 'bonus.dlamountlimit',
        'donortimes_bonus' => 'bonus.donortimes',
        'emailnotify_smtp' => 'smtp.emailnotify',
        'enableattach_attachment' => 'attachment.enableattach',
        'enablebitbucket_main' => 'main.enablebitbucket',
        'enabledonation' => 'main.donation',
        'enablelocation_tweak' => 'tweak.enablelocation',
        'enablenfo_main' => 'main.enablenfo',
        'enableoffer' => 'main.showoffer',
        'enablesqldebug_tweak' => 'tweak.enablesqldebug',
        'enabletooltip_tweak' => 'tweak.enabletooltip',
        'euderatio_account' => 'account.euderatio',
        'eudl_account' => 'account.eudl',
        'euprratio_account' => 'account.euprratio',
        'eutime_account' => 'account.eutime',
        'expirefree_torrent' => 'torrent.expirefree',
        'expirehalfleech_torrent' => 'torrent.expirehalfleech',
        'expirenormal_torrent' => 'torrent.expirenormal',
        'expirethirtypercentleech_torrent' => 'torrent.expirethirtypercentleech',
        'expiretwoup_torrent' => 'torrent.expiretwoup',
        'expiretwoupfree_torrent' => 'torrent.expiretwoupfree',
        'expiretwouphalfleech_torrent' => 'torrent.expiretwouphalfleech',
        'extfour_attachment' => 'attachment.extfour',
        'extone_attachment' => 'attachment.extone',
        'extthree_attachment' => 'attachment.extthree',
        'exttwo_attachment' => 'attachment.exttwo',
        'exuderatio_account' => 'account.exuderatio',
        'exudl_account' => 'account.exudl',
        'exuprratio_account' => 'account.exuprratio',
        'exutime_account' => 'account.exutime',
        'fivegbupload_bonus' => 'bonus.fivegbupload',
        'forummanage_class' => 'authority.forummanage',
        'forumpostsperpage' => 'main.postsperpage',
        'forumtopicsperpage_main' => 'main.topicsperpage',
        'freebecome_torrent' => 'torrent.freebecome',
        'getInvitesByPromotion_class' => 'account.getInvitesByPromotion',
        'halfleechbecome_torrent' => 'torrent.halfleechbecome',
        'hotdays_torrent' => 'torrent.hotdays',
        'hotseeder_torrent' => 'torrent.hotseeder',
        'httpdirectory_attachment' => 'attachment.httpdirectory',
        'icplicense_main' => 'main.icplicense',
        'iniupload_main' => 'main.iniupload',
        'invite_count' => 'main.invite_count',
        'invite_timeout' => 'main.invite_timeout',
        'invitesystem' => 'main.invitesystem',
        'iplog1' => 'tweak.iplog1',
        'iuderatio_account' => 'account.iuderatio',
        'iudl_account' => 'account.iudl',
        'iuprratio_account' => 'account.iuprratio',
        'iutime_account' => 'account.iutime',
        'iv' => 'security.iv',
        'l_bonus' => 'bonus.l',
        'largepro_torrent' => 'torrent.largepro',
        'log_class' => 'authority.log',
        'logo_main' => 'main.logo',
        'mainversion_code' => 'code.mainversion',
        'makepost_bonus' => 'bonus.makepost',
        'max_dead_torrent_time' => 'main.max_dead_torrent_time',
        'maxdlsystem' => 'main.maxdlsystem',
        'maxip' => 'security.maxip',
        'maxloginattempts' => 'security.maxloginattempts',
        'maxnewsnum_main' => 'main.maxnewsnum',
        'maxseeding_bonus' => 'bonus.maxseeding',
        'maxsubsize_main' => 'main.maxsubsize',
        'metadescription_tweak' => 'tweak.metadescription',
        'metakeywords_tweak' => 'tweak.metakeywords',
        'minoffervotes' => 'main.minoffervotes',
        'movetorrent_class' => 'authority.movetorrent',
        'neverdelete_account' => 'account.neverdelete',
        'neverdeletepacked_account' => 'account.neverdeletepacked',
        'newsmanage_class' => 'authority.newsmanage',
        'nmderatio_account' => 'account.nmderatio',
        'nmdl_account' => 'account.nmdl',
        'nmprratio_account' => 'account.nmprratio',
        'nmtime_account' => 'account.nmtime',
        'nodetect_security' => 'security.nodetect',
        'normalbecome_torrent' => 'torrent.normalbecome',
        'nzero_bonus' => 'bonus.nzero',
        'offermanage_class' => 'authority.offermanage',
        'offeruptimeout_main' => 'main.offeruptimeout',
        'offervote_bonus' => 'bonus.offervote',
        'offervotetimeout_main' => 'main.offervotetimeout',
        'onegbupload_bonus' => 'bonus.onegbupload',
        'oneinvite_bonus' => 'bonus.oneinvite',
        'perseeding_bonus' => 'bonus.perseeding',
        'pollmanage_class' => 'authority.pollmanage',
        'pollvote_bonus' => 'bonus.pollvote',
        'postmanage_class' => 'authority.postmanage',
        'prfmanage_class' => 'authority.prfmanage',
        'prorules_torrent' => 'torrent.prorules',
        'psdlfive_account' => 'account.psdlfive',
        'psdlfour_account' => 'account.psdlfour',
        'psdlone_account' => 'account.psdlone',
        'psdlthree_account' => 'account.psdlthree',
        'psdltwo_account' => 'account.psdltwo',
        'psratiofive_account' => 'account.psratiofive',
        'psratiofour_account' => 'account.psratiofour',
        'psratioone_account' => 'account.psratioone',
        'psratiothree_account' => 'account.psratiothree',
        'psratiotwo_account' => 'account.psratiotwo',
        'puderatio_account' => 'account.puderatio',
        'pudl_account' => 'account.pudl',
        'puprratio_account' => 'account.puprratio',
        'putime_account' => 'account.putime',
        'randomfree_torrent' => 'torrent.randomfree',
        'randomhalfleech_torrent' => 'torrent.randomhalfleech',
        'randomthirtypercentdown_torrent' => 'torrent.randomthirtypercentdown',
        'randomtwoup_torrent' => 'torrent.randomtwoup',
        'randomtwoupfree_torrent' => 'torrent.randomtwoupfree',
        'randomtwouphalfdown_torrent' => 'torrent.randomtwouphalfdown',
        'ratiolimit_bonus' => 'bonus.ratiolimit',
        'receivethanks_bonus' => 'bonus.receivethanks',
        'registration' => 'main.registration',
        'releasedate_code' => 'code.releasedate',
        'savedirectory_attachment' => 'attachment.savedirectory',
        'savedirectorytype_attachment' => 'attachment.savedirectorytype',
        'saythanks_bonus' => 'bonus.saythanks',
        'sbmanage_class' => 'authority.sbmanage',
        'securelogin' => 'security.securelogin',
        'securetracker' => 'security.securetracker',
        'seebanned_class' => 'authority.seebanned',
        'seeding_leeching_time_calc_start' => 'main.seeding_leeching_time_calc_start',
        'sendinvite_class' => 'authority.sendinvite',
        'showforumstats_main' => 'main.showforumstats',
        'showlastxforumposts_main' => 'main.showlastxforumposts',
        'showlastxtorrents_main' => 'main.showlastxtorrents',
        'showpolls_main' => 'main.showpolls',
        'showshoutbox_main' => 'main.showshoutbox',
        'showstats_main' => 'main.showstats',
        'showtrackerload' => 'main.showtrackerload',
        'signup_timeout' => 'main.signup_timeout',
        'sizefour_attachment' => 'attachment.sizefour',
        'sizeone_attachment' => 'attachment.sizeone',
        'sizethree_attachment' => 'attachment.sizethree',
        'sizetwo_attachment' => 'attachment.sizetwo',
        'smtp_from' => 'smtp.smtp_from',
        'smtp_host' => 'smtp.smtp_host',
        'smtp_port' => 'smtp.smtp_port',
        'smtpaddress' => 'smtp.smtpaddress',
        'smtpport' => 'smtp.smtpport',
        'smtptype' => 'smtp.smtptype',
        'sptime' => 'main.sptime',
        'sqldebug_tweak' => 'tweak.sqldebug',
        'staffmem_class' => 'authority.staffmem',
        'starttopic_bonus' => 'bonus.starttopic',
        'submanage_class' => 'authority.submanage',
        'subversion_code' => 'code.subversion',
        'taxpercentage_bonus' => 'bonus.taxpercentage',
        'tengbupload_bonus' => 'bonus.tengbupload',
        'thirtypercentleechbecome_torrent' => 'torrent.thirtypercentleechbecome',
        'thumbheight_attachment' => 'attachment.thumbheight',
        'thumbnailtype_attachment' => 'attachment.thumbnailtype',
        'thumbquality_attachment' => 'attachment.thumbquality',
        'thumbwidth_attachment' => 'attachment.thumbwidth',
        'titlekeywords_tweak' => 'tweak.titlekeywords',
        'topten_class' => 'authority.topten',
        'torrent_dir' => 'main.torrent_dir',
        'torrenthistory_class' => 'authority.torrenthistory',
        'torrentmanage_class' => 'authority.torrentmanage',
        'torrentnameprefix' => 'main.torrentnameprefix',
        'torrentonpromotion_class' => 'authority.torrentonpromotion',
        'torrentsticky_class' => 'authority.torrentsticky',
        'torrentstructure_class' => 'authority.torrentstructure',
        'twoupbecome_torrent' => 'torrent.twoupbecome',
        'twoupfreebecome_torrent' => 'torrent.twoupfreebecome',
        'twouphalfleechbecome_torrent' => 'torrent.twouphalfleechbecome',
        'tzero_bonus' => 'bonus.tzero',
        'updateextinfo_class' => 'authority.updateextinfo',
        'upload_class' => 'authority.upload',
        'uploaderdouble_torrent' => 'torrent.uploaderdouble',
        'uploadsub_class' => 'authority.uploadsub',
        'uploadtorrent_bonus' => 'bonus.uploadtorrent',
        'userbar_class' => 'authority.userbar',
        'userprofile_class' => 'authority.userprofile',
        'uuderatio_account' => 'account.uuderatio',
        'uudl_account' => 'account.uudl',
        'uuprratio_account' => 'account.uuprratio',
        'uutime_account' => 'account.uutime',
        'verification' => 'main.verification',
        'viewanonymous_class' => 'authority.viewanonymous',
        'viewhistory_class' => 'authority.viewhistory',
        'viewinvite_class' => 'authority.viewinvite',
        'viewnfo_class' => 'authority.viewnfo',
        'viewuserlist_class' => 'authority.viewuserlist',
        'vipstatus_bonus' => 'bonus.vipstatus',
        'vuderatio_account' => 'account.vuderatio',
        'vudl_account' => 'account.vudl',
        'vuprratio_account' => 'account.vuprratio',
        'vutime_account' => 'account.vutime',
        'waitsystem' => 'main.waitsystem',
        'website_code' => 'code.website',
        'where_tweak' => 'tweak.where',
    ];

    /**
     * Seeds the settings behind a legacy flat key list: keys that mirror a
     * `settings` row are written via `Settings::saveBatch` (what migrated
     * `SiteConfig` call sites read); anything else is still pushed into
     * `$globals` for the runtime keys that have no settings row.
     *
     * @param  array<string, mixed>  $values
     */
    protected function seedTestSettings(array $values, ?Globals $globals = null): void
    {
        $byCategory = [];
        foreach ($values as $key => $value) {
            $setting = self::LEGACY_SETTING_KEYS[$key] ?? null;
            if ($setting !== null) {
                [$category, $name] = explode('.', $setting, 2);
                $byCategory[$category][$name] = is_float($value) ? (string) $value : $value;
            } elseif ($globals !== null) {
                $globals->set($key, $value);
            }
        }
        foreach ($byCategory as $category => $pairs) {
            Settings::saveBatch($category, $pairs);
        }
        Settings::resetCache();
    }
}
